version: '3'
services:
  database:
    image: postgres:alpine
    container_name: "spend_tracker_database"
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
